name: testing environments
on: push

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'building...'

  deploy-staging:
    name: Deploying to Staging
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v2
      - run: echo 'deploying to staging with ${{ secrets.ENV_SECRET }}...'
  
  deploy-production:
    name: Deploying to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2
      - run: echo 'deploying to production with ${{ secrets.ENV_SECRET }}...'
